### ISSUE TITLE
Support for WebSockets

### ISSUE THREAD

**Issue by jwric** [UkoeHB/renet2#16]
Hello @UkoeHB , I'm trying to use renet2 as part of a Godot 3.5 project with [gdnative](https://github.com/godot-rust/gdnative) bindings. I would like to compile for the web, and as far as I've seen, Godot 3.5 only supports WebSockets and WebRTC for html5 exports. A WebSocket implementation for renet2 seems relatively simple as most of the logic for an http based protocol is already implemented in the current WebTransport one. 

I think it should work if I can get a custom renet2 transport client that works using gdnative's `WebSocketClient` bindings.

I suggest to add at least a server implementation of WebSockets to renet2. As for a client implementation to add to renet2, maybe there could be one for native builds that uses `tungstenite`, and another for wasm builds that uses wasm-bindgen bindings similar to the WebTransport client impl.

**Comment by mirsella** [comment]
another reason to support websocket, is that webtransport is not supported for now on safari. Which mean no support for default mac and ios AFAIK

**Comment by UkoeHB** [comment]
@mirsella It's a valid use-case, but is it actually possible to reliably detect if a browser will work with WebTransport? Other than trying to ping a webtransport server.

**Comment by mirsella** [comment]
only use websocket, or at minimum detect the OS (ios/macos, or other) is still possible ?
its possible to have a js function that check if webtransport is supported directly no ? like check if the class exist or something like that ?

**Comment by UkoeHB** [comment]
> only use websocket, or at minimum detect the OS (ios/macos, or other) is still possible ?

I'd rather only use websocket as a last resort, because it is not very compatible with the `netcode` protocol.

> its possible to have a js function that check if webtransport is supported directly no ? like check if the class exist or something like that ?

I'd also want to check if `ServerCertHash` is supported, since for my project I want to use that.

> this would not be something part of this crate, but user code anyway

Agreed, and the lack of solution isn't a reason to block a websocket impl. I might add it this weekend. But I was wondering if you had a nice solution :)

**Comment by mirsella** [comment]
yeah websocket would just be a fallback is webtransport is not supported on some devices.

to check if its supported, i think literally just `if ('WebTransport' in window)` should work ? i didn't test it as i dont have ios devices, but logically it shoudl work, and thats what i seems to find on internet

**Comment by UkoeHB** [comment]
Ok I did some research, and looks like the `web-sys` `WebTransport` constructor will fail if webtransport is not supported. On top of that, if `serverCertificateHashes` are not supported, then the constructor will also [error](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport/WebTransport#exceptions).

So it should be sufficient to attempt to construct a fake `WebTransport` (either with or without cert hashes) and if that fails fall back to websockets.

**Comment by UkoeHB** [comment]
Added detection functions in https://github.com/UkoeHB/renet2/commit/3e7125d2e3d5113acbc1fccadc562cae9b8043f0. Unfortunately it won't detect browser bugs like https://github.com/BiagioFesta/wtransport/issues/241.

**Comment by mirsella** [comment]
looking at the issue you linked, from what I understood it's not a bug but the latest version of browser are blocking self signed certificate something like that I think for "security"

**Comment by UkoeHB** [comment]
> looking at the issue you linked, from what I understood it's not a bug but the latest version of browser are blocking self signed certificate something like that I think for "security"

I don't think so. If they didn't want to support self-signed certs then they would not support the `serverCertificateHashes` feature at all, but they do claim to support it.

**Comment by mirsella** [comment]
well it's still possible to use self signed certificate by enabling a feature flag in the settings, so they're not removing it, just blocking it by default. removing serverCertificatesHashes would break a lot of things imo.

anyway, I don't think this is important for this issue.
for example, the aeronet crate examples all use encryption, without even setting up self signed certificate

**Comment by UkoeHB** [comment]
Implemented in https://github.com/UkoeHB/renet2/commit/4acb9bc9971e815bcdaff529928899842b61a852
