### ISSUE TITLE
RenetChannelsExt doesn't seem to be implemented for RepliconChannels

### ISSUE THREAD

**Issue by mirsella** [UkoeHB/renet2#18]
hello

i was trying to use bevy_replicon_renet2, but i didnt manage to call the RenetChannelsExt method:
```
error[E0599]: no method named `get_server_configs` found for struct `bevy::prelude::Res<'_, bevy_replicon::prelude::RepliconChannels>` in the current scope
  --> src/main.rs:66:55
   |
66 |                 let server_channels_config = channels.get_server_configs();
   |                                                       ^^^^^^^^^^^^^^^^^^ method not found in `Res<'_, RepliconChannels>`

error[E0599]: no method named `get_client_configs` found for struct `bevy::prelude::Res<'_, bevy_replicon::prelude::RepliconChannels>` in the current scope
  --> src/main.rs:67:55
   |
67 |                 let client_channels_config = channels.get_client_configs();
   |                                                       ^^^^^^^^^^^^^^^^^^ method not found in `Res<'_, RepliconChannels>`

error[E0599]: no method named `get_server_configs` found for struct `bevy::prelude::Res<'_, bevy_replicon::prelude::RepliconChannels>` in the current scope
   --> src/main.rs:101:55
    |
101 |                 let server_channels_config = channels.get_server_configs();
    |                                                       ^^^^^^^^^^^^^^^^^^ method not found in `Res<'_, RepliconChannels>`

error[E0599]: no method named `get_client_configs` found for struct `bevy::prelude::Res<'_, bevy_replicon::prelude::RepliconChannels>` in the current scope
   --> src/main.rs:102:55
    |
102 |                 let client_channels_config = channels.get_client_configs();
    |                                                       ^^^^^^^^^^^^^^^^^^ method not found in `Res<'_, RepliconChannels>`

warning: unused import: `RenetChannelsExt`
  --> src/main.rs:23:5
   |
23 |     RenetChannelsExt, RepliconRenetPlugins,
   |     ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
   ```
you can replicate this issue by doing this:
`cargo new a`
cargo.toml:
```toml
[package]
name = "a"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_replicon = "0.28.3"
bevy_replicon_renet2 = { git = "https://github.com/UkoeHB/renet2", tag = "0.0.5", features = [
  "wt_server_transport",
  "wt_client_transport",
  "native_transport",
] }
clap = { version = "4.5.18", features = ["derive"] }
serde = "1.0.210"
```
And copy the examples/simple_box.rs to main.rs.
and that's it.

In the example, it probably works because it's the same crate or something like that

thanks !

**Comment by mirsella** [comment]
i was thinking its because its a Res<RepliconChannels>, but no, even with a pure RepliconChannels it doesn't work.
also, it work in the example with a Res<RepliconChannels> so the issue is not that.
i think its just being no another crate, the RenetChannelsExt for RepliconChannels might to apply correctly ?

**Comment by mirsella** [comment]
it seems that bevy_replicon_renet is working

**Comment by mirsella** [comment]
After further investigation, I think i found why.
since bevy_replicon_renet2 is a sub crate the workspace renet2, the trait implementation probably work only for the other member of the crate.
thats why bevy_replicon_renet work, because it is its own package.
i tried moving out bevy_replicon_renet2 out of renet2 folder, and it works.

i don't know if its fixable with the current renet2 project architecture.
if i don't manage to fix it, i guess ill create a git repo with just the bevy_replicon_renet2 crate.

**Comment by mirsella** [comment]
im now using my fork https://github.com/mirsella/bevy_replicon_renet2 which works, it just remove the workspace and directly but bevy_replicon_renet2 at the root

**Comment by mirsella** [comment]
Oh, it works on main, but not with the tag 0.0.5.
do you know which commit fix it ? im curious

**Comment by UkoeHB** [comment]
> Oh, it works on main, but not with the tag 0.0.5.

Oh hey, sorry about this. I updated the `bevy_replicon` dependency but didn't make a new tag yet. You got that error due to `bevy_replicon_renet2` using a different version than your project. I will make a new tag now!

**Comment by mirsella** [comment]
ohh thats why...
thanks !

**Comment by UkoeHB** [comment]
@mirsella tag `0.0.6` has been pushed.
