### ISSUE TITLE
example on how to use WebTransport

### ISSUE THREAD

**Issue by mirsella** [UkoeHB/renet2#19]
hello !

i was trying to use bevy_replicon_renet2, and i was wondering how we should get a Handle to pass to `WebTransportServer` it seems to be a tokio Handle, but bevy use another async runtime for its task pool ?
maybe a simple example of how to setup a webtransportserver/client would be useful for noobie like me.

thanks

**Comment by mirsella** [comment]
also, i didn't manage to build the doc for renet2 with the client web transport stuff as its locked behind target_family wasm which is good, but so i don't know how or if its possible to make them appear in rustdoc.
having a example on how to use the webtransport stuff or having them in a local doc build would be a really useful

**Comment by UkoeHB** [comment]
> maybe a simple example of how to setup a webtransportserver/client would be useful for noobie like me.

The example here shows setting up a WebTransport server and client: https://github.com/UkoeHB/renet2/tree/main/examples . It is necessary to use `tokio` on the server because our WebTransport dependency currently uses tokio. Some day I'd like to switch to [nevy](https://github.com/DrewRidley/nevy) which won't require a runtime.

> also i dont know if there is a way of building the doc for multiple target_arch at the same time, (native, wt_server_transport AND wt_client_transport) that would be useful.

I'll work on fixing this today.

**Comment by UkoeHB** [comment]
Ok after some investigation there is no apparent way to improve the ergonomics of generating docs locally. I added a section to the README with the commands you figured out.

**Comment by mirsella** [comment]
nice ! I think a example with web transport (just a copy paste of simple_box) would be helpful for new comers.
I can do a pr if I manage to use it (just wondering what the right way of getting a Tokio runtime handle in bevy

**Comment by UkoeHB** [comment]
> I think a example with web transport (just a copy paste of simple_box) would be helpful for new comers.

In case you missed my other comment, [there is an example](https://github.com/UkoeHB/renet2/blob/0d787728e354c59ba1480cb97731c99274019371/examples/echo_server_cross/src/main.rs#L42) showing how to make a WebTransport server. It is not much different from a normal server.

If you PR another example showing bevy integration, I'd be happy to add that too :)

**Comment by mirsella** [comment]
oh nice didn't see it as I was searching more for a bevy specific example.
I was thinking of a "right" way of doing this for maximum performance/deficiency between the Tokio runtime and bevy runtime.

as they're multi thread I guess I can just start tokio and insert a ref to it as a resource.

thanks !

**Comment by UkoeHB** [comment]
> I was thinking of a "right" way of doing this for maximum performance/deficiency between the Tokio runtime and bevy runtime.

Unfortunately there's no good answer here except to replace the webtransport server implementation entirely. Which I definitely want to do some day :)

**Comment by mirsella** [comment]
> Which I definitely want to do some day :)
nice !
I guess bevy's async task compute pool can be used ?

**Comment by UkoeHB** [comment]
> I guess bevy's async task compute pool can be used ?

Don't need any async, can just poll for updates every tick. [nevy](https://github.com/DrewRidley/nevy) would handle that for us but careful integration work and analysis is needed for correctness.
