### ISSUE TITLE
Update compatible versions list for bevy_replicon_renet2 

### ISSUE THREAD

**Issue by adrylain** [UkoeHB/renet2#21]
I believe bevy_replicon_renet2 has been updated to support Bevy 0.15 and Replicon 0.29 as per the Cargo.toml, but the compatible version list in the README is not updated. I personally search for these lists when I am trying to choose a crate, so it would be beneficial to correct it.

**Comment by UkoeHB** [comment]
Fixed in https://github.com/UkoeHB/renet2/commit/37482c636a48e901f0b0ad06a8166210941c8468
