### ISSUE TITLE
unresolved import `bevy_renet2::netcode::NativeSocket`

### ISSUE THREAD

**Issue by tortoise501** [UkoeHB/renet2#22]
Hello,
I have an issue where I cannot replicate the example provided for bevy_renet2 crate. I cannot use bevy_renet2::netcode::NativeSocket. While searching for solutions, I found NativeSocket in renet2_netcode, but still couldn't use it. Any help will be appreciated. Thank you.

**Comment by UkoeHB** [comment]
Sorry about that, fixed in https://github.com/UkoeHB/renet2/commit/c301a22845c0adfe3e379a2fa75b7ce5d9c0f81e
